### ISSUE TITLE
Some services are not able to be constructed

### ISSUE THREAD

**Issue by SilentRage47** [AlanPBourke/CoravelWindowsService#1]
It doesn't work, getting this error when I try to run it:

`'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: CoravelWindowsService.Invocables.EverySecondsInvocableJob Lifetime: Transient ImplementationType: CoravelWindowsService.Invocables.EverySecondsInvocableJob': Unable to resolve service for type 'CoravelWindowsService.JobDefinitions.EverySecondsJobDefinition' while attempting to activate 'CoravelWindowsService.Invocables.EverySecondsInvocableJob'.)`

**Comment by AlanPBourke** [comment]
Are you using an unchanged version of the repository? I've just pulled and built it in a clean VM and it works fine.
